services:
  financial_tracker_database:
    image: postgres:17
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  financial_tracker_app:
    image: financial_tracker_app
    entrypoint: ./entrypoint.sh
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - financial_tracker_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@financial_tracker_database:5432/app_db

volumes:
  data: